config/routes.rb
Rails.application.routes.draw do

  root to: 'locations#index'

  resources :locations, only: [:index] do
    resources :hikes, only: [:index, :show, :new, :create]
  end

  resources :users, only: [:new, :create]

  namespace :admin do
    resources :categories
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/categories_hike.rb
class CategoriesHike < ActiveRecord::Base
  belongs_to :hike
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categories_hikes
  has_many :hikes, through: :categories_hikes

  validates :name, presence: true
end

app/models/hike.rb
class Hike < ActiveRecord::Base
  belongs_to :location
  has_many :categories_hikes
  has_many :categories, through: :categories_hikes

  validates :date_hiked, presence: true
  validates :route, presence: true
  validates :description, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :hikes

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validates :role, presence: true

  enum role: ["default", "admin"]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: '/public/404' unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category #{@category.name} saved!"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Updated #{@category.name} Category!"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController

  def index
    @location = Location.find(params[:location_id])
    @hikes = @location.hikes
  end

  def show
    @hike = Hike.find(params[:id])
    @location = @hike.location
  end

  def new
    @location = Location.find(params[:location_id])
    @hike = @location.hikes.new
  end

  def create
    @location = Location.find(params[:location_id])
    @hike = @location.hikes.new(hike_params)
    if @hike.save
      flash[:notice] = "Your hike was added!"
      redirect_to location_hike_path(@location, @hike)
    else
      flash.now[:notice] = @hike.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def hike_params
    params.require(:hike).permit(
      :date_hiked,
      :route,
      :distance,
      :elevation_gain,
      :highest_point,
      :description,
      category_ids:[]
    )
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:notice] = "Invalid username or password. Try Again."
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Goodbye!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Hi, #{@user.username}. Your account was created!"
      redirect_to root_path
    else
      flash.now[:notice] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/edit.html.erb
<h1>Edit Category</h1>

<%= form_for [:admin, @category] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit %>
<% end %>

<%= link_to "Back to All Categories", admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1 class="text-center">Categories</h1>

<ul class="list-group">
  <% @categories.each do |category| %>
    <li class="list-group-item">
      <%= link_to "#{category.name}", admin_category_path(category) %>
      <%= link_to "Edit", edit_admin_category_path(category), class: "btn btn-default" %>
      <%= link_to "Delete", admin_category_path(category), method: :delete, class: "btn btn-default" %>
    </li>
  <% end %>
</ul>

<%= link_to "Create New Category", new_admin_category_path, class: "btn btn-primary" %>

app/views/admin/categories/new.html.erb
<h1>Create New Category</h1>

<%= form_for [:admin, @category] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit %>
<% end %>

<%= link_to "Back to All Categories", admin_categories_path %>

app/views/admin/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

<h3>Hikes with this category</h3>

<ul class="list-group">
  <% @category.hikes.each do |hike| %>
    <li class="list-group-item"><%= link_to "#{hike.route} - #{hike.date_hiked}", location_hike_path(hike.location, hike) %></li>
  <% end %>
</ul>

app/views/hikes/index.html.erb
<h1 class="text-center"><%= @location.name %></h1>

<ul class="list-group">
  <% @hikes.each do |hike| %>
    <li class="list-group-item">
      <%= link_to "#{hike.date_hiked} - #{hike.route}", location_hike_path(@location, hike) %>
    </li>
  <% end %>
</ul>


<%= link_to "Add Your #{@location.name} Hike", new_location_hike_path(@location), class: "btn btn-primary" %>

app/views/hikes/new.html.erb
<h1>Create your <%= @location.name %> Hike</h1>

<%= form_for [@location, @hike] do |f| %>
  <div class="form-group">
    <%= f.label :date_hiked %>
    <%= f.date_field :date_hiked, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :route %>
    <%= f.text_field :route, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :distance %>
    <%= f.text_field :distance, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :elevation_gain %>
    <%= f.text_field :elevation_gain, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :highest_point %>
    <%= f.text_field :highest_point, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: "15" %>
  </div>

  <div class="checkbox">
    <%= f.label "Hike Categories" %><br />
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |c| %>
      <div class="checkbox">
        <%= c.check_box %>
        <%= c.label %>
      </div>
    <% end %>
  </div>

  <%= f.submit "Create Hike", class: "btn btn-default" %>
<% end %>

<%= link_to "Back to All #{@location.name} Hikes", location_hikes_path(@location) %>

app/views/hikes/show.html.erb
<h1><%= @location.name %></h1>

<h3>Date Hiked: <%= @hike.date_hiked %></h3>

<table class="table">
  <tr>
    <td>Route</td>
    <td><%= @hike.route %></td>
  </tr>
  <tr>
    <td>Distance</td>
    <td><%= @hike.distance %></td>
  </tr>
  <tr>
    <td>Elevation Gain</td>
    <td><%= @hike.elevation_gain %></td>
  </tr>
  <tr>
    <td>Highest Point</td>
    <td><%= @hike.highest_point %></td>
  </tr>
  <tr>
    <td>Categories</td>
    <td><%= @hike.categories.to_a.map {|category| category.name}.join(", ") %></td>
  </tr>
</table>

<p><%= @hike.description %></p>

<%= link_to "Back To All #{@location.name} Hikes", location_hikes_path(@location) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrailBox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

  <nav class="navbar navbar-default">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><%= link_to "Locations", locations_path %></li>
        <% if current_user %>
          <p class="navbar-text">Hi, <%= current_user.username %></p>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>


<% flash.each do |name, message| %>
  <%= content_tag :div, message, id: "flash_#{name}" %>
<%  end %>


<%= yield %>

</body>
</html>

app/views/locations/index.html.erb
<h1 class="text-center">Locations</h1>

<ul class="list-group">
  <% @locations.each do |location| %>
    <li class="list-group-item">
      <span class="badge"><%= location.hikes.count %> Hikes</span>
      <%= link_to location.name, location_hikes_path(location) %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create Your New Account</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.submit "Create Account" %>
<% end %>